lunetics_locale:
    allowed_locales: %languagechooserlocales%
    cookie:
        set_on_change: true
        secure: true
    guessing_order:
        - query
        - cookie
        - session
        - browser
        - router
