services:
    kunstmaan_languagechooser.languagechooserrouter:
        class: Kunstmaan\LanguageChooserBundle\Router\LanguageChooserRouter
        arguments: ["@service_container"]
        tags:
            - { name: router, priority: 100 }

    twig.extension.your_extension_name:
        class: Kunstmaan\LanguageChooserBundle\Twig\Extension\LanguageChooserExtension
        calls:
             - [setLanguageChooserLanguages, [%kunstmaan_language_chooser.languagechooserlocales%]]
        tags:
            - { name: twig.extension }